### ISSUE TITLE
Discuss commit synchronisation

### ISSUE THREAD

**Issue by tipragot** [solipr/solipr#7]
I have multiple question that we should answer before we continue development:
- What method do we use to manage witch commit is applied to a repository, is there a central user that had authority and control which commit is applied or is there a vote system so that for example, if more than 50 % of the repository owner valid the commit, it is applied?
- When a commit is valided and applied to the repository, is it possible to remove it ? And if so how do we sync this change?

**Comment by CoCoSol007** [comment]
- For the first question, I think a system of owners is better.
- We can create a system like git revert to place a commit on top of the one we want to delete, undoing the changes.

**Comment by tipragot** [comment]
If we use an ownership system, is it possible for a repository to have multiple owners? If the owners are not connected, is it still possible to push changes that others can see? If so, how?

Regarding revert commits, how do we handle reverting a commit that resolves a conflict? I don’t think it is possible using only Insert and Delete changes. Can you clarify what you think?

**Comment by CoCoSol007** [comment]
- A system where every repo has an owner, and by cloning that repo, you become the owner, as if to contribute to a repo, you had to fork it. If you want to push into a repo, you have to ask the owner of this fork.

- Mmh, if you cancel a commit that handles a conflict, it goes back into a state of conflict.

**Comment by tipragot** [comment]
I think it would be simpler if there was a way to simply push changes as "pull request" directly to a repo without having to fork it, also, i think, it could be better if we are able to access the changes even if the owner of the repo is offline, if so we will need to implement a gossip algorithm so that multiple clients stores the repo and can serve it to others.

How can you cancel a conflict resolution? How can you go back to the state of conflict by only Insert and/or Remove operations? I think that simply removing the change could be a better solution, and to synchronize the currently active changes, we can use a [CRDT](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type) for example.

**Comment by tipragot** [comment]
An other issue I want to discuss here is : will there be public repositories? If that's the case, how can we share them? Maybe we should look at [distributed search engines](https://en.wikipedia.org/wiki/Distributed_search_engine) to look at how they handle the problem.

**Comment by CoCoSol007** [comment]
It might be nice to have a gossip algorithm system but how do you implement that without a centrale unite ?

Using CRDT is a good idea for conflict resolution.

Well, I'm going to look at the decentralized search engine, but I think that's a good idea.
